### ISSUE TITLE
No javadoc created from constructors.

### ISSUE THREAD

**Issue by jhameier** [dnault/therapi-runtime-javadoc#37]
Found that there is no way to pull the javadoc from a constructor. 

Test Class:
```
/**
 * This is the class level javadoc.
 */
public class TestClass {

  /**
   * This is the ctor javadoc.
   */
  public TestClass() {}

  /**
   * This is the method javadoc.
   */
  public void testMethod() {}
}
```

Driver:
```
import com.github.therapi.runtimejavadoc.ClassJavadoc;
import com.github.therapi.runtimejavadoc.RuntimeJavadoc;

public class Test {
  public static void main(String[] args) {
    ClassJavadoc classJavadoc = RuntimeJavadoc.getJavadoc(TestClass.class);
    System.out.println(classJavadoc);
  }
}
```

Output
```
ClassJavadoc {
   name='TestClass', 
   comment=This is the class level javadoc., 
   fields=[], 
   methods=[MethodJavadoc {
                        name='testMethod', 
                        paramTypes='[]', 
                        comment=This is the method javadoc., 
                        params=[], 
                        exceptions=[],
                        other=[], 
                        returns=, 
                        seeAlso=[]
                   }], 
   seeAlso=[], 
   other=[]
}
```

**Comment by dnault** [comment]
Hi John, thanks for reporting this. It seems like a reasonable feature request.

One way to expose it would be to add a `getConstructors()` method to `ClassJavadoc`. It could probably return a `List<MethodJavadoc>` since there's not much difference between a Constructor and a regular method as far as Javadoc is concerned.

Out of curiosity, what is the use case for reading constructor Javadoc?

**Comment by dnault** [comment]
Hi John, would you be interested in submitting a pull request, either for this or #38 ?  (I just want to give you an opportunity to contribute if that's something you want to do.)

**Comment by jhameier** [comment]
> One way to expose it would be to add a getConstructors() method to ClassJavadoc

Yes that what I was thinking/hoping that it would be an easy fix since there is no real difference between a Ctor and Method javadoc.

> Out of curiosity, what is the use case for reading constructor Javadoc?

We develop a dynamic aircraft simulator and optionally loaded classes are used to enhance the simulator capabilities depending on customer needs. There could be multiple constructors that are used to instantiate a single Optionally loaded class so there is a need to specifically have javadoc explaining the  use of input parameters and how these affect what the optionally loaded class does.

My approach at writing javadoc for this project is to use the class level javadoc as a broad overview of what the class has to offer and ctor level javadoc is more targeted to the specifics of what the ctor offers. Using this approach and your library, I'm building documentation programatically. This allows our hands on customers to have concise documentation of extended simulator capabilities.

I used the returned javadoc to produce a markdown document and by extending the CustomFormatter, I can control some of the formatting and create well formatted documentation that is much easier to read then pure javadoc especially for non-technical folks.  We also use flexmark to convert to html so that it can be read into swing components and made available at runtime in the simulator but my thought was to possibly extend the CustomFormatter and possibly even eliminate having to use that library altogether.

> would you be interested in submitting a pull request

Unfortunately my schedule doesn't give me much free time these days. I'm currently working towards my Masters and simulation work has kept me quite busy over the last several months. But I will keep it in mind.

**Comment by dnault** [comment]
Very cool, sounds like you're working on an interesting project!

> I was thinking/hoping that it would be an easy fix since there is no real difference between a Ctor and Method javadoc.

Turns out you were correct! The next release will support constructor javadoc. Release date is TBD (I want to see if it makes sense to address #38 in the same release) but should be within a few days.

**Comment by dnault** [comment]
@jhameier Version 0.11.0 is live on Maven Central with fixes for all of the issues you reported so far. Thanks for pushing this project forward.

**Comment by elaineSaijan** [comment]
Hello @dnault 
I am running into this error below. It parses my class and parses it into json the docs, methods, even enums,  but the input stream does not read in my constructors which causes this error. Would it be possible to modify the readMethodDocs function to ignore if the methods JsonValue methodsValue == null or something like that?

```
java.lang.NullPointerException
	at com.github.therapi.runtimejavadoc.internal.JsonJavadocReader.readMethodDocs(JsonJavadocReader.java:56)
	at com.github.therapi.runtimejavadoc.internal.JsonJavadocReader.readClassJavadoc(JsonJavadocReader.java:30)
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.parseJavadocResource(RuntimeJavadoc.java:103)
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.getJavadoc(RuntimeJavadoc.java:86)
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.getJavadoc(RuntimeJavadoc.java:38)
	at org.mitre.caasd.ttfs.web.util.JavadocUtil.printJavadoc(JavadocUtil.java:20)
	at org.mitre.caasd.ttfs.web.util.JavadocUtilTest.testJavaDoc(JavadocUtilTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```

**Comment by elaineSaijan** [comment]
this is an example of the json doc produced for a class, as you can see there is no field called "constructor":
`{"doc":" test javadoc","fields":[{"name":"var1","doc":" test javadoc"},{"name":"var2","doc":" test javadoc"}],"enumConstants":[],"methods":[]}`
