### ISSUE TITLE
IllegalArgumentException when getting Javadoc for nested class that has no Javadoc

### ISSUE THREAD

**Issue by dnault** [dnault/therapi-runtime-javadoc#69]
Affected version: 0.14.0

```
Class `javasource.foo.DocumentedClass.NestedWithoutJavadoc` does not match class doc for `javasource.foo.DocumentedClass$NestedWithoutJavadoc`
java.lang.IllegalArgumentException: Class `javasource.foo.DocumentedClass.NestedWithoutJavadoc` does not match class doc for `javasource.foo.DocumentedClass$NestedWithoutJavadoc`
	at com.github.therapi.runtimejavadoc.ClassJavadoc.createEnhancedClassJavadoc(ClassJavadoc.java:102)
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.getJavadoc(RuntimeJavadoc.java:55)
        ...
```

**Comment by dnault** [comment]
Thank you to @yanxiyue who initially reported this in PR https://github.com/dnault/therapi-runtime-javadoc/pull/68 ❤️
